title = "Tract"
theme = "tract"
baseURL = "https://tract-docs.dev"
disableKinds = ["taxononmy", "taxonomyTerm"]

[params]
description = "A Hugo theme for ambitious open source projects"

[markup.highlight]
style = "paraiso-dark"

[[params.buttons.main]]
text = "Getting started"
icon = "rocket"
url = "/docs/getting-started"

[[params.buttons.main]]
text = "Docs"
icon = "information-circle"
url = "/docs"

[[params.fonts]]
name = "Alata"
sizes = [300, 400, 600, 700]
type = "sans_serif"

[[params.fonts]]
name = "Inconsolata"
sizes = [300, 400, 600, 700]
type = "monospace"

[params.social.twitter]
handle = "lucperkins"

[params.social.github]
repo = "tract-docs/tract"

[params.social.slack]
channel = "tract-docs"

[[menu.docs]]
name = "Foo"
url = "/foo"