theme = "tract"
baseURL = "https://tract-docs.dev"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
copyright = "Luc Perkins"

[taxonomies]
tag = "tags"

[params]
icon_set = "ionicons"
version = "0.1.0-alpha"

[params.colors]
primary = "#880e4f"
secondary = "#1e88e5"

[markup.highlight]
style = "dracula"

[outputs]
home = ["HTML", "JSON"]

[[params.fonts]]
name = "Alata"
sizes = [300, 400, 600, 700]
type = "sans_serif"

[[params.fonts]]
name = "Roboto Mono"
sizes = [300, 400, 600, 700]
type = "monospace"

[params.social.twitter]
handle = "lucperkins"

[params.social.github]
repo = "tract-docs/tract-docs.dev"

[params.social.slack]
channel = "tract-docs"

[params.social.youtube]
channel = "UCvqbFHwN-nwalWPjPUKpvTA"

[params.social.linkedin]
id = "luc-perkins-a087b322"

[params.social.facebook]
username = "lucperkins"

[[menu.main]]
name = "Docs"
identifier = "docs"
url = "/docs"
weight = 1

[[menu.main]]
name = "Getting started"
parent = "docs"
url = "/docs/getting-started"
weight = 1

[[menu.main]]
name = "Internationalization"
parent = "docs"
url = "/docs/i18n"
weight = 2

[languages.en]
languageName = "English"
contentDir = "content/en"
weight = 1
title = "Tract"

[languages.en.params]
description = "A Hugo theme for ambitious documentation projects"

[languages.de]
languageName = "Deutsch"
contentDir = "content/de"
weight = 2
title = "Traktat"

[languages.de.params]
description = "Irgendwas auf Deutsch statt auf Englisch"

[languages.de.params.social.twitter]
handle = "DFB_Team_EN"

[[languages.de.menus.main]]
name = "Doku"
url = "/dokumentation"
weight = 1

[languages.fr]
languageName = "Français"
contentDir = "content/fr"
weight = 3
title = "Tract"

[languages.fr.params]
description = "Quelque chose en français ici"

[languages.fr.params.social.twitter]
handle = "france"

[[languages.fr.menus.main]]
name = "Documentation"
url = "/documentation"
weight = 1
