title = "Tract"
theme = "tract"
baseURL = "https://tract-docs.dev"
disableKinds = ["taxononmy", "taxonomyTerm"]

[params]
description = "A Hugo theme for ambitious open source projects"
#texture = "Bright squares"
github_repo = "tract-docs/tract-docs.dev"

[markup.highlight]
style = "fruity"

[[params.buttons.main]]
text = "Getting started"
icon = "rocket"
url = "/docs/getting-started"

[[params.buttons.main]]
text = "Docs"
icon = "information-circle"
url = "/docs"

[[params.fonts]]
name = "Alata"
sizes = [300, 400, 600, 700]
type = "sans_serif"

[[params.fonts]]
name = "Roboto Mono"
sizes = [300, 400, 600, 700]
type = "monospace"
