title = "Tract"
theme = "tract"
baseURL = "https://tract-docs.dev"
disableKinds = ["taxononmy", "taxonomyTerm"]

[params]
description = "A Hugo theme for ambitious open source projects"

[markup.highlight]
style = "paraiso-dark"

[[params.buttons.main]]
text = "Getting started"
icon = "rocket"
url = "/docs/getting-started"
color = "primary"
inverted = true
outlined = true

[[params.buttons.main]]
text = "Docs"
icon = "information-circle"
url = "/docs"
color = "secondary"

[[params.buttons.main]]
text = "Repo"
icon = "logo-github"
url = "https://github.com/tract-docs/tract"

[[params.fonts]]
name = "Alata"
sizes = [300, 400, 600, 700]
type = "sans_serif"

[[params.fonts]]
name = "Inconsolata"
sizes = [300, 400, 600, 700]
type = "monospace"

[params.social.twitter]
handle = "lucperkins"

[params.social.github]
repo = "tract-docs/tract"

[params.social.slack]
channel = "tract-docs"

[[menu.main]]
name = "Documentation"
url = "/docs"
weight = 1

[[menu.main]]
name = "Community"
url = "/community"
weight = 2

[[menu.main]]
name = "Project"
url = "/project"
weight = 3

[[menu.docs]]
name = "Foo"
url = "/foo"
identifier = "foo"

[[menu.docs]]
name = "Bar"
url = "/bar"
parent = "foo"