title = "Tract"
theme = "tract"
baseURL = "https://tract-docs.dev"
defaultContentLanguage = "en"

[taxonomies]
tag = "tags"

[params]
description = "A Hugo theme for ambitious documentation projects"
#icon_set = "ionicons"

[params.colors]
primary = "#1976d2"
secondary = "#0d47a1"

[markup.highlight]
style = "paraiso-dark"

[outputs]
home = [ "HTML", "JSON" ]

[[params.buttons.main]]
text = "Getting started"
icon = "rocket"
url = "/docs/getting-started"
color = "primary"
inverted = true
outlined = true

[[params.buttons.main]]
text = "Docs"
icon = "information-circle"
url = "/docs"
color = "secondary"

[[params.buttons.main]]
text = "Repo"
icon = "logo-github"
url = "https://github.com/tract-docs/tract"

[[params.fonts]]
name = "Alata"
sizes = [300, 400, 600, 700]
type = "sans_serif"

[[params.fonts]]
name = "Inconsolata"
sizes = [300, 400, 600, 700]
type = "monospace"

[params.social.twitter]
handle = "lucperkins"

[params.social.github]
repo = "tract-docs/tract"

[params.social.slack]
channel = "tract-docs"

[params.social.youtube]
channel = "UCvqbFHwN-nwalWPjPUKpvTA"

[params.social.linkedin]
id = "luc-perkins-a087b322"

[params.social.facebook]
username = "lucperkins"

[[menu.main]]
name = "Community"
url = "/community"
weight = 1

[[menu.main]]
name = "Project"
url = "/project"
weight = 2

[[menu.main]]
name = "External"
url = "https://example.org"
weight = 3

[[menu.main]]
name = "Docs"
identifier = "docs"
url = "/docs"
weight = 4

[[menu.main]]
name = "Getting started"
parent = "docs"
url = "/docs/getting-started"
weight = 1

[[menu.docs]]
name = "Foo"
url = "/foo"
identifier = "foo"

[[menu.docs]]
name = "Bar"
url = "https://google.com"
parent = "foo"
