theme = "tract"
baseURL = "https://tract-docs.dev"
disableKinds = ["taxonomy", "taxonomyTerm"]
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[taxonomies]
tag = "tags"

[params]
icon_set = "ionicons"

[params.home.buttons]
inverted = true

[params.colors]
primary = "#1976d2"
secondary = "#0d47a1"

[markup.highlight]
style = "paraiso-dark"

[outputs]
home = ["HTML", "JSON"]

[[params.fonts]]
name = "Lato"
sizes = [300, 400, 600, 700]
type = "sans_serif"

[[params.fonts]]
name = "Inconsolata"
sizes = [300, 400, 600, 700]
type = "monospace"

[params.social.twitter]
handle = "lucperkins"

[params.social.github]
repo = "tract-docs/tract-docs.dev"

[params.social.slack]
channel = "tract-docs"

[params.social.youtube]
channel = "UCvqbFHwN-nwalWPjPUKpvTA"

[params.social.linkedin]
id = "luc-perkins-a087b322"

[params.social.facebook]
username = "lucperkins"

[[menu.main]]
name = "Community"
url = "/community"
weight = 0

[[menu.main]]
name = "Project"
url = "/project"
weight = 1

[[menu.main]]
name = "External"
url = "https://example.org"
weight = 2

[[menu.main]]
name = "Docs"
identifier = "docs"
url = "/docs"
weight = 3

[[menu.main]]
name = "Getting started"
parent = "docs"
url = "/docs/getting-started"
weight = 0

[[menu.docs]]
name = "Foo"
url = "/foo"
identifier = "foo"

[[menu.docs]]
name = "Bar"
url = "https://google.com"
parent = "foo"

[languages.en]
languageName = "English"
contentDir = "content/en"
weight = 1
title = "Tract"

[languages.en.params]
description = "A Hugo theme for ambitious documentation projects"

[languages.de]
languageName = "Deutsch"
contentDir = "content/de"
weight = 2
title = "Traktat"

[languages.de.params]
description = "Irgendwas auf Deutsch statt auf Englisch"

[languages.de.params.social.twitter]
handle = "DFB_Team_EN"

[[languages.de.menus.main]]
name = "Projekt"
url = "/projekt"
weight = 0

[[languages.de.menus.main]]
name = "Doku"
url = "/dokumentation"
weight = 1

[languages.fr]
languageName = "Français"
contentDir = "content/fr"
weight = 3
title = "Tract"

[languages.fr.params.social.twitter]
handle = "france"

[[languages.fr.menus.main]]
name = "Documentation"
url = "/documentation"
weight = 1

[[languages.fr.menus.main]]
name = "Projet"
url = "/projet"
weight = 2