title = "Tract"
theme = "tract"
disableKinds = ["taxononmy", "taxonomyTerm"]

[params]
description = "A Hugo theme for ambitious open source projects"

[[params.fonts]]
name = "Open Sans"
sizes = [300, 400, 600, 700]
type = "sans_serif"

[[params.fonts]]
name = "Roboto Mono"
sizes = [300, 400, 600, 700]
type = "monospace"