title = "Tract"
theme = "tract-material"
baseURL = "https://tract-docs.dev"
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params.colors]
primary = "purple"

[[params.navbar.menu]]
icon = "file_download"
label = "Download"

[[params.navbar.menu]]
icon = "print"
label = "Print this page"

[[params.navbar.menu]]
icon = "bookmark"
label = "Bookmark this page"

