[build]
publish = "public"
command = "make production-build"

[build.environment]
HUGO_VERSION = "0.62.0"

[context.deploy-preview]
command = "make preview-build"

[context.branch-deploy]
command = "make preview-build"

[[plugins]]
package = "netlify-plugin-a11y"

[[plugins]]
package = "netlify-plugin-checklinks"
